apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: nginx-deployment nginx=nginx:1.24.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:           #定義Pod 們統一的設定模板
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80

