# create deployment yaml  sample for spring boot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: hello-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 可以比desire replicas多出來的Pod數量
      maxUnavailable: 1  # 在任何時間點只有一個Pod可以處於不可用狀態
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-container
          # image: docker.io/library/spring-hellowworld-image-ms:latest
          image: 384533264466.dkr.ecr.ap-northeast-1.amazonaws.com/spring-hellowworld-image:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: 
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"                    
# ---
# #service:
# apiVersion: v1
# kind: Service
# metadata:
#   name: spring-boot-app-service
#   labels:
#     app: spring-boot-app
# spec: 
#   selector:
#     app: spring-boot-app
#   ports:
#   type: NodePort
  



