# Package stage
FROM maven:3.9.5-eclipse-temurin-17-focal AS build

WORKDIR /app

COPY . .

#RUN mvn -f /app/pom.xml clean package -DskipTests
CMD ["./mvnw", "spring-boot:run"]

# Build stage
FROM eclipse-temurin:17-jre-alpine

WORKDIR /usr/local/lib

COPY --from=build /app/target/spring-boot-docker-0.0.1-SNAPSHOT.jar spring-boot-docker-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","spring-boot-docker-0.0.1-SNAPSHOT.jar"]