apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
    version: v1.0.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
      version: v1.0.1
  template:
    metadata:
      labels:
        app: petclinic
        version: v1.0.1
    spec:
      containers:
      - name: petclinic
        image: spring2go/spring-petclinic:1.0.1.RELEASE
        ports:
        - containerPort: 8080
