apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
    version: 1.0.1.RELEASE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      version: 1.0.1.RELEASE
  template:
    metadata:
      labels:
        app: petclinic
        version: 1.0.1.RELEASE
    spec:
      containers:
      - name: petclinic
        image: spring2go/spring-petclinic:1.0.1.RELEASE
        ports:
        - containerPort: 8080
