apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: petclinic
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: petclinic
    version: v1.0.0 #修改selector version標記為v1.0.1
  type: NodePort
